# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Inacistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('1', 'ASISTENTE'), ('2', 'INASISTENCIA JUSTIFICADA'), ('3', 'INASISTENCIA INJUSTIFICADA'), ('4', 'RETARDOS/TIEMPO')], max_length=2, null=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(blank=True, choices=[('1', 'ASISTENTE'), ('2', 'INASISTENCIA JUSTIFICADA'), ('3', 'INASISTENCIA INJUSTIFICADA'), ('4', 'RETARDOS/TIEMPO')], max_length=2, null=True)),
            ],
            options={
                'db_table': 'inacistencia',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Femenino')], max_length=2, null=True)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Cargo')),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.AddField(
            model_name='inacistencia',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Personal'),
        ),
    ]
